ClinicaVeterinaria/Controllers/AnimaliController.cs
using ClinicaVeterinaria.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClinicaVeterinaria.Controllers
{
    [Authorize(Roles = "Veterinario")]
    public class AnimaliController : Controller
    {
        DBContext db = new DBContext();
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index([Bind(Include = "Nome,Tipologia,ColoreMantello,DataNascita,Microchip,NumeroMicrochip,NomeProprietario,CognomeProprietario")] Animali animali)
        {

            var animale = new Animali()
            {
                Nome = animali.Nome,
                Tipologia = animali.Tipologia,
                ColoreMantello = animali.ColoreMantello,
                DataNascita = animali.DataNascita,
                Microchip = animali.Microchip,
                NumeroMicrochip = animali.NumeroMicrochip,
                NomeProprietario = animali.NomeProprietario,
                CognomeProprietario = animali.CognomeProprietario
            };
            db.Animali.Add(animale);
            db.SaveChanges();
            TempData["ConfermaAnimale"] = true;
            return RedirectToAction("Lista");
        }
       
        public ActionResult Dettagli(int ID)
        {
            Animali animale = db.Animali.Where(x => x.ID == ID).FirstOrDefault();
            ViewBag.Animale = animale;
            return View();
        }
        public ActionResult Lista()
        {
            List<Animali> lista = db.Animali.ToList();
            ViewBag.Animali = lista;
            return View();
        }
        [HttpPost]
        public ActionResult Modifica([Bind(Include = "ID,Nome,Tipologia,ColoreMantello,DataNascita,Microchip,NumeroMicrochip,NomeProprietario,CognomeProprietario")] Animali animali)
        {
            var animale = db.Animali.Where(x => x.ID == animali.ID).FirstOrDefault();
            if (animale != null)
            {
                animale.Nome = animali.Nome;
                animale.Tipologia = animali.Tipologia;
                animale.ColoreMantello = animali.ColoreMantello;
                if (animali.DataNascita != null)
                {
                    animale.DataNascita = animali.DataNascita;
                }
                if (animali.Microchip != null)
                {
                    animale.Microchip = animali.Microchip;
                }
                animale.NumeroMicrochip = animali.NumeroMicrochip;
                animale.NomeProprietario = animali.NomeProprietario;
                animale.CognomeProprietario = animali.CognomeProprietario;
                db.SaveChanges();
            }


            return RedirectToAction("Lista");
        }
        [HttpPost]
        public ActionResult Elimina(int ID)
        {
            var animali = db.Animali.Where(x => x.ID == ID).FirstOrDefault();
            db.Animali.Remove(animali);
            db.SaveChanges();
            return RedirectToAction("Lista");

        }

    }
}

ClinicaVeterinaria/Controllers/AuthController.cs
using ClinicaVeterinaria.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace ClinicaVeterinaria.Controllers
{
    public class AuthController : Controller
    {

        DBContext db = new DBContext();

        public ActionResult Login()
        {
            if (User.Identity.IsAuthenticated) return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login( Utenti user, bool? keepLogged)
        {
            bool keepUserLogged = keepLogged.HasValue && keepLogged.Value;
            var loggedUser = db.Utenti.FirstOrDefault(u => u.Email == user.Email);
            if (loggedUser != null)
            {
                bool validPassword = BCrypt.Net.BCrypt.Verify(user.PasswordHash, loggedUser.PasswordHash);
                if (validPassword)
                {
                    FormsAuthentication.SetAuthCookie(loggedUser.Id.ToString(), keepUserLogged);
                    return RedirectToAction("Index", "Home");
                }
            }

            TempData["ErrorLogin"] = true;
            return RedirectToAction("Login");
        }

        public ActionResult Register()
        {

            if (User.Identity.IsAuthenticated) return RedirectToAction("Index", "Home");
            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "Nome,Cognome,Email,PasswordHash")]RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var existingUser = db.Utenti.FirstOrDefault(u => u.Email == model.Email);
                if (existingUser == null)
                {
                    var hashedPassword = BCrypt.Net.BCrypt.HashPassword(model.PasswordHash);

                    var newUser = new Utenti
                    {
                        Nome = model.Nome,
                        Cognome = model.Cognome,
                        Email = model.Email,
                        PasswordHash = hashedPassword,
                        Ruolo = "Farmacista"
                    };
                    db.Utenti.Add(newUser);
                    db.SaveChanges();

                    FormsAuthentication.SetAuthCookie(newUser.Id.ToString(), false);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "An account with this email already exists.");
                }
            }
            return View(model);
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

ClinicaVeterinaria/Controllers/RicoveriController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using ClinicaVeterinaria.Models;
using System.IO;
using System.Web;

namespace ClinicaVeterinaria.Controllers
{
    [Authorize(Roles = "Veterinario")]
    public class RicoveriController : Controller
    {
        private DBContext db = new DBContext();

        public ActionResult Index()
        {
            var ricoveri = db.Ricoveri.Include(r => r.Animali).ToList();
            return View(ricoveri);
        }

        public ActionResult Details(int id)
        {
            var ricovero = db.Ricoveri.Include(r => r.Animali).SingleOrDefault(r => r.ID == id);
            if (ricovero == null)
            {
                return HttpNotFound();
            }
            return View(ricovero);
        }

        public ActionResult Aggiungi()
        {
            ViewBag.AnimaliList = new SelectList(db.Animali.ToList(), "ID", "Nome");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Aggiungi([Bind(Include = "ID,IDAnimale,DataInizio,DataFine,Descrizione,Foto")] Ricoveri ricovero, HttpPostedFileBase Foto)
        {
            if (ModelState.IsValid)
            {
                if(Foto != null && Foto.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(Foto.FileName);
                    var path = Path.Combine(Server.MapPath("~/Assets/uploads"), fileName);
                    Foto.SaveAs(path);

                    ricovero.Foto = Path.Combine("~/Assets/uploads", fileName);
                }
                db.Ricoveri.Add(ricovero);
                db.SaveChanges();
                return RedirectToAction("Index");
       
            }

            ViewBag.AnimaliList = new SelectList(db.Animali.ToList(), "ID", "Nome");
            return View(ricovero);
        }


        public ActionResult Modifica(int id)
        {
            var ricovero = db.Ricoveri.Find(id);
            if (ricovero == null)
            {
                return HttpNotFound();
            }

            ViewBag.AnimaliList = new SelectList(db.Animali.ToList(), "ID", "Nome", ricovero.IDAnimale);
            return View(ricovero);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Modifica([Bind(Include = "ID,IDAnimale,DataInizio,DataFine,Descrizione,Foto")] Ricoveri ricovero, HttpPostedFileBase Foto)
        {
            if (ModelState.IsValid)
            {
                if(Foto != null && Foto.ContentLength > 0)
                {
                    if(!string.IsNullOrEmpty(ricovero.Foto))
                    {
                        var oldFilePath = Server.MapPath(ricovero.Foto);
                        if(System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }

                    var fileName = Path.GetFileName(Foto.FileName);
                    var path = Path.Combine(Server.MapPath("~/Assets/uploads"), fileName);
                    Foto.SaveAs(path);

                    ricovero.Foto = $"~/Assets/uploads/{fileName}";
                }
                db.Entry(ricovero).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AnimaliList = new SelectList(db.Animali.ToList(), "ID", "Nome", ricovero.IDAnimale);
            return View(ricovero);
        }


        public ActionResult Elimina(int id)
        {
            var ricovero = db.Ricoveri.Find(id);
            if (ricovero == null)
            {
                return HttpNotFound();
            }
            return View(ricovero);
        }

        [HttpPost, ActionName("Elimina")]
        [ValidateAntiForgeryToken]
        public ActionResult EliminaConfermato(int id)
        {
            var ricovero = db.Ricoveri.Find(id);
            if (ricovero == null)
            {
                return HttpNotFound();
            }
            db.Ricoveri.Remove(ricovero);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ClinicaVeterinaria/Controllers/VisiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using ClinicaVeterinaria.Models;

namespace ClinicaVeterinaria.Controllers
{
    [Authorize(Roles = "Veterinario")]
    public class VisiteController : Controller
    {
        private readonly DBContext db = new DBContext();

        // GET: Visite
        public ActionResult Index()
        {
            var visiteList = db.Visite.ToList();

            return View(visiteList);
        }

        public ActionResult Registra()

        {
            ViewBag.AnimaliDropDown = db.Animali.Select(a => new SelectListItem
            {
                Text = a.Nome,
                Value = a.ID.ToString(),
            }).ToList();
            List<Animali> animaliList = db.Animali.ToList();
            ViewBag.Animali = animaliList;
            return View();
        }

        public ActionResult GetVisiteByAnimaleId(int animaleId)
        {
            var visite = db.Visite
                .Where(v => v.IDAnimale == animaleId)
                .OrderByDescending(v => v.DataVisita)
                .ToList();

            return Json(visite, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registra([Bind(Include = "IDAnimale,DataVisita,EsameObiettivo,CuraPrescritta")]  Visite visita)
        {

            if (ModelState.IsValid)
            {
                var animale = db.Animali.Find(visita.IDAnimale);
                if (animale != null)
                {
                    try
                    {
                        db.Visite.Add(visita);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    catch (Exception ex)
                    {

                        ModelState.AddModelError(string.Empty, "Si è verificato un errore durante l'aggiunta della visita.");
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "L'animale specificato non esiste.");
                }
            }

            ViewBag.Animali = new SelectList(db.Animali.ToList(), "ID", "Nome", visita.IDAnimale);
            return View(visita);
        }

    }
}

ClinicaVeterinaria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Clinica Veterinaria</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Assets/Style.css" rel="stylesheet" />
</head>
<body>
    <div class="d-flex flex-column min-vh-100">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm custom-nav">
            <div class="container">
                <img src="/Assets/uploads/logo_veterinario.png" alt="Logo" class="navbar-logo" width="60" height="60" />
                @Html.ActionLink("Clinica Veterinaria", "Index", "Home", new { area = "" }, new { @class = "navbar-brand text-custom" })
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Veterinario"))
                        {

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Animali
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Lista Animali", "Lista", "Animali", new { area = "" }, new { @class = "dropdown-item text-custom" })</li>
                                    <li>@Html.ActionLink("Aggiungi Animale", "Index", "Animali", new { area = "" }, new { @class = "dropdown-item text-custom" })</li>
                                </ul>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Visite
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Lista Visite", "Index", "Visite", new { area = "" }, new { @class = "dropdown-item text-custom" })</li>
                                    <li>@Html.ActionLink("Aggiungi Visita", "Registra", "Visite", new { area = "" }, new { @class = "dropdown-item text-custom" })</li>
                                </ul>
                            </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Ricoveri
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Lista Ricoveri", "Index", "Ricoveri", new { area = "" }, new { @class = "dropdown-item" })</li>
                            <li>@Html.ActionLink("Aggiungi Ricovero", "Aggiungi", "Ricoveri", new { area = "" }, new { @class = "dropdown-item" })</li>
                            <li>@Html.ActionLink("Rimborso Mensile", "RimborsoMensile", "Rimborso", new { area = "" }, new { @class = "dropdown-item" })</li>
                           
                        </ul>
                    </li>

                        }

                        <li>@Html.ActionLink("Tracking Ricovero", "Index", "RicercaRicovero", new { area = "" }, new { @class = "nav-link" })</li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Farmacista"))
                        {

                            <li>@Html.ActionLink("Farmacia", "Index", "Farmacia", new { area = "" }, new { @class = "nav-link" })</li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Medicinali Venduti
                                </a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Per Data", "VenditePerData", "MedicinaliVenduti", new { area = "" }, new { @class = "dropdown-item" })</li>
                                    <li>@Html.ActionLink("Per Cliente", "VenditePerCliente", "MedicinaliVenduti", new { area = "" }, new { @class = "dropdown-item" })</li>
                                </ul>
                            </li>
                        }

                    </ul>
                    <div>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <a href="@Url.Action("Login", "Auth", new { area = "" })" class="btn btn-custom">Login</a>
                            <a href="@Url.Action("Register", "Auth", new { area = "" })" class="btn btn-outline-light text-custom py-2">Register</a>
                        }
                        else
                        {

                            <form action="@Url.Action("Logout", "Auth")" method="post" style="display: inline;">
                                @Html.AntiForgeryToken()
                                <button type="submit" class="btn btn-custom">Logout</button>
                            </form>
                        }
                    </div>
                </div>
            </div>
        </nav>
        <div class="container body-content flex-grow-1">
            @RenderBody()

        </div>
        
        <footer class="text-custom text-center">
            <hr />
            <p class="mb-5">&copy; @DateTime.Now.Year - Clinica Veterinaria</p>
        </footer>
    </div>

        <script src="~/Scripts/popper.min.js"></script>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")

        <script>

            document.addEventListener("DOMContentLoaded", function () {
                var dropdownToggleList = [].slice.call(document.querySelectorAll('[data-bs-toggle="dropdown"]'));
                dropdownToggleList.forEach(function (dropdownToggleEl) {
                    new bootstrap.Dropdown(dropdownToggleEl);
                });
            });
        </script>
        @RenderSection("scripts", required: false)
</body>
</html>